const $ = (x: string) => document.getElementById(x) as HTMLElement;

const d = {
  flowers: $("flowers"),
  pollen: $("pollen"),
  nectar: $("nectar"),
  honey: $("honey"),

  flowersPS: $("flowersPS"),
  pollenPS: $("pollenPS"),
  nectarPS: $("nectarPS"),
  honeyPS: $("honeyPS"),

  freeBees: $("freeBees"),
  foragerBees: $("foragerBees"),
  honeyBees: $("honeyBees"),

  flowerFields: $("flowerFields"),
  flowerFieldPrice: $("flowerFieldPrice"),
  buyFlowerField: $("buyFlowerField") as HTMLButtonElement,
  quickBuyFlowerField: $("slowBuyFlowerField") as HTMLButtonElement,
  bees: $("bees"),
  beePrice: $("beePrice"),
  buyBee: $("buyBee") as HTMLButtonElement,
  quickBuyBee: $("quickBuyBee") as HTMLButtonElement,
  hives: $("hives"),
  hivePrice: $("hivePrice"),
  buyHive: $("buyHive") as HTMLButtonElement,
  quickBuyHive: $("quickBuyHive") as HTMLButtonElement,

  set0ForagerBees: $("set0ForagerBees") as HTMLButtonElement,
  minusForagerBees: $("minusForagerBees") as HTMLButtonElement,
  plusForagerBees: $("plusForagerBees") as HTMLButtonElement,
  maxForagerBees: $("maxForagerBees") as HTMLButtonElement,
  set0HoneyBees: $("set0HoneyBees") as HTMLButtonElement,
  minusHoneyBees: $("minusHoneyBees") as HTMLButtonElement,
  plusHoneyBees: $("plusHoneyBees") as HTMLButtonElement,
  maxHoneyBees: $("maxHoneyBees") as HTMLButtonElement,

  // requiredBeesToSacrifice: $("requiredBeesToSacrifice"),

  donateToPollenGod: $("donateToPollenGod") as HTMLButtonElement,
  donateToNectarGod: $("donateToNectarGod") as HTMLButtonElement,
  donateToHoneyGod: $("donateToHoneyGod") as HTMLButtonElement,
  donateToFlowerGod: $("donateToFlowerGod") as HTMLButtonElement,
  donateToCapitalistGod: $("donateToCapitalistGod") as HTMLButtonElement,

  pollenGodTributesToGet: $("pollenGodTributesToGet"),
  nectarGodTributesToGet: $("nectarGodTributesToGet"),
  honeyGodTributesToGet: $("honeyGodTributesToGet"),
  flowerGodTributesToGet: $("flowerGodTributesToGet"),
  capitalistGodTributesToGet: $("capitalistGodTributesToGet"),

  // pollenGodTributes: $("pollenGodTributes"),
  // nectarGodTributes: $("nectarGodTributes"),
  // honeyGodTributes: $("honeyGodTributes"),
  // flowerGodTributes: $("flowerGodTributes"),
  // capitalistGodTributes: $("capitalistGodTributes"),

  nextPollenGodTribute: $("nextPollenGodTribute"),
  nextNectarGodTribute: $("nextNectarGodTribute"),
  nextHoneyGodTribute: $("nextHoneyGodTribute"),
  nextFlowerGodTribute: $("nextFlowerGodTribute"),
  nextCapitalistGodTribute: $("nextCapitalistGodTribute"),

  beesWrapper: $("beesWrapper"),
  sacrificeWrapper: $("sacrificeWrapper"),
  flowerFieldsEffect: $("flowerFieldsEffect"),
  hivesEffect: $("hivesEffect"),
  beesEffect: $("beesEffect"),

  flowerPSStat: $("flowerPSStat"),
  pollenPSStat: $("pollenPSStat"),
  nectarPSStat: $("nectarPSStat"),
  honeyPSStat: $("honeyPSStat"),
  beehiveSpaceEffectStat: $("beehiveSpaceEffectStat"),
  beeSpaceEffectStat: $("beeSpaceEffectStat"),

  beehiveSpaceEffectStatS: $("beehiveSpaceEffectStatS"),
  beeSpaceEffectStatS: $("beeSpaceEffectStatS"),

  totalflowers: $("totalflowers"),
  totalpollen: $("totalpollen"),
  totalnectar: $("totalnectar"),
  totalhoney: $("totalhoney"),

  totalTributes: $("totalTributes"),
  neededBeesToSacrifice: $("neededBeesToSacrifice"),

  totalBeesToSacrificeFromTributes: $("totalBeesToSacrificeFromTributes"),
  pollenGodTributesAfterSacrifice: $("pollenGodTributesAfterSacrifice"),
  nectarGodTributesAfterSacrifice: $("nectarGodTributesAfterSacrifice"),
  honeyGodTributesAfterSacrifice: $("honeyGodTributesAfterSacrifice"),
  flowerGodTributesAfterSacrifice: $("flowerGodTributesAfterSacrifice"),
  capitalistGodTributesAfterSacrifice: $("capitalistGodTributesAfterSacrifice"),

  money: $("money"),
  totalmoney: $("totalmoney"),
  moneyPS: $("moneyPS"),

  m: {
    0: $("m0"),
    1: $("m1"),
    2: $("m2"),
    3: $("m3"),
    4: $("m4"),
    5: $("m5"),
    6: $("m6"),
    7: $("m7"),
    8: $("m8"),
    9: $("m9"),
    10: $("m10"),
    11: $("m11"),
    12: $("m12"),
    13: $("m13"),
  },

  m0e: $("m0e"),
  m1e: $("m1e"),
  m2e: $("m2e"),
  m3e: $("m3e"),
  m4e: $("m4e"),
  m5e: $("m5e"),
  m6e: $("m6e"),
  m7e: $("m7e"),
  m8e: $("m8e"),
  m9e: $("m9e"),
  m10e: $("m10e"),
  m11e: $("m11e"),
  m12e: $("m12e"),
  m13e: $("m13e"),

  m0d: $("m0d"),
  m1d: $("m1d"),
  m2d: $("m2d"),
  m3d: $("m3d"),
  m4d: $("m4d"),
  m5d: $("m5d"),
  m6d: $("m6d"),
  m7d: $("m7d"),
  m8d: $("m8d"),
  m9d: $("m9d"),
  m10d: $("m10d"),
  m11d: $("m11d"),
  m12d: $("m12d"),
  m13d: $("m13d"),

  m0t: $("m0t"),
  m1t: $("m1t"),
  m2t: $("m2t"),
  m3t: $("m3t"),
  m4t: $("m4t"),
  m5t: $("m5t"),
  m6t: $("m6t"),
  m7t: $("m7t"),
  m8t: $("m8t"),
  m9t: $("m9t"),
  m10t: $("m10t"),
  m11t: $("m11t"),
  m12t: $("m12t"),
  m13t: $("m13t"),

  // m7effect: $("m6effect"),
  honeyCheckBox: $("honeyCheckBox") as HTMLInputElement,

  reqBeesToSacTitle: $("reqBeesToSacTitle"),
  pernamentTributeEffects: $("pernamentTributeEffects"),
  gameCompletion: $("gameCompletion"),

  flowerswrapper: $("flowerswrapper"),
  pollenwrapper: $("pollenwrapper"),
  nectarwrapper: $("nectarwrapper"),
  honeywrapper: $("honeywrapper"),
  moneywrapper: $("moneywrapper"),
  beeswrapper: $("beeswrapper"),
  hivewrapper: $("hivewrapper"),

  foragerbeestext: $("foragerbeestext"),
  honeybeestext: $("honeybeestext"),

  foragerbeeswrapper: $("foragerbeeswrapper"),
  honeybeeswrapper: $("honeybeeswrapper"),
  flowerfieldwrapper: $("flowerfieldwrapper"),
  quickbuyhivewrapper: $("quickbuyhivewrapper"),
  tributeswrapper: $("tributeswrapper"),

  flowerpsstatwrapper: $("flowerpsstatwrapper"),
  foragerstatwrapper: $("foragerstatwrapper"),
  honeybeestatwrapper: $("honeybeestatwrapper"),
  beehivestatwrapper: $("beehivestatwrapper"),
  fifthbeestatwrapper: $("fifthbeestatwrapper"),
  recomended: $("recomended"),
  disaplyeverything: $("disaplyeverything") as HTMLInputElement,

  pollengodwrapper: $("pollengodwrapper"),
  nectargodwrapper: $("nectargodwrapper"),
  honeygodwrapper: $("honeygodwrapper"),
  flowergodwrapper: $("flowergodwrapper"),
  capitalistgodwrapper: $("capitalistgodwrapper"),

  foragerbeestextunderline: $("foragerbeestextunderline"),
  honeybeestextunderline: $("honeybeestextunderline"),

  autosaves: $("autosaves") as HTMLInputElement,

  saveButton: $("saveButton"),
  loadButton: $("loadButton"),

  ticksLeft: $("ticksLeft"),
  offlineTicks: $("offlineTicks"),

  flowerConsumptionStat: $("flowerConsumptionStat"),
  nectarConsumptionStat: $("nectarConsumptionStat"),
  honeyWorthStat: $("honeyWorthStat"),

  offlineTicksSpeed5: $("offlineTicksSpeed5") as HTMLInputElement,
  offlineTicksSpeed10: $("offlineTicksSpeed10") as HTMLInputElement,

  honeystatwrapper: $("honeystatwrapper"),

  toggleDarkmode: $("toggleDarkmode") as HTMLInputElement,
  body: document.querySelector("body") as HTMLBodyElement,
};
//todo shorten these names?
